### ISSUE TITLE
我可以贡献双系统安装的内容吗

### ISSUE THREAD

**Issue by Firestar-Reimu** [ArchLinuxStudio/ArchLinuxTutorial#113]
https://github.com/ArchLinuxStudio/ArchLinuxTutorialComments/issues/52#issuecomment-945331476

这里有人问有没有双系统教程，你们说不支持

我自己写了一个实时更新的双系统安装教程 https://blog.firestar-reimu.top/ArchLinux-Installation/ 或者在 https://github.com/Firestar-Reimu/Arch-and-Manjaro-KDE-Installation

请问我可以发布PR来贡献双系统安装的内容吗？

**Comment by ryosukeeeeee** [comment]
本项目不包含对非Linux系统的支持。

**Comment by Firestar-Reimu** [comment]
emmm就如果你去看 https://blog.firestar-reimu.top/ArchLinux-Installation/ 的话，没有windows系统安装，只是在同时存在windows的情况下如何安装linux

算了，提个pull request你们自己看好了
