### ISSUE TITLE
主页挂了

### ISSUE THREAD

**Issue by awarewen** [ArchLinuxStudio/ArchLinuxTutorial#25]
archlinuxstudio.github.io/archlinuxtutorial/#/
![Screenshot_20210529_185245_com tencent mtt](https://user-images.githubusercontent.com/53365857/120067668-6c2a0600-c042-11eb-82fa-f0a212b7267f.jpg)

**Comment by wallena3** [comment]
archlinuxstudio.github.io/ArchLinuxTutorial/#/
not
archlinuxstudio.github.io/archlinuxtutorial/#/

**Comment by wallena3** [comment]
@awarewen 同时确认你的网络环境 github page站点在中国某些地区被屏蔽污染。 如无问题请关闭issue
