### ISSUE TITLE
After arch iso is selected from the grub option, the screen is black and the boot cannot be completed

### ISSUE THREAD

**Issue by zengyaoqi** [ArchLinuxStudio/ArchLinuxTutorial#40]
在arch iso启动时grub可以显示,但选择进入后就会黑屏
gpu 3070ti
cpu 2600
而且似乎安装任何linux都如此
在opensuse镜像选择之后跑一些代码然后黑屏
在manjaro启动镜像时卡在如图所示的状态
![linux](https://user-images.githubusercontent.com/84330226/128634654-6d1d4da0-7e48-40ab-90e6-92faee264c7c.jpg)

**Comment by TakoTakoo** [comment]
@zengyaoqi 检查下镜像md5,同时确保镜像盘刻录方式正确，并检查主板security boot是否关闭

**Comment by zengyaoqi** [comment]
@TakoTakoo 已经解决了,是驱动问题,只能用nomodeset进去
