### ISSUE TITLE
Qv2ray 已经停止更新

### ISSUE THREAD

**Issue by T2hhbmEK** [ArchLinuxStudio/ArchLinuxTutorial#42]
[Qv2ray](https://github.com/Qv2ray/Qv2ray) 已经停更，建议更换其他工具如 [v2rayA](https://github.com/v2rayA/v2rayA)。

**Comment by livrth** [comment]
> [Qv2ray](https://github.com/Qv2ray/Qv2ray) 已经停更，建议更换其他工具如 [v2rayA](https://github.com/v2rayA/v2rayA)。

提 issue/comment 前请先认真阅读[文档](https://archlinuxstudio.github.io/ArchLinuxTutorial/#/rookie/fxckGFW?id=%e6%9c%89%e5%85%b3-qv2ray-%e7%9a%84%e6%9b%bf%e4%bb%a3)

**Comment by junmoxiao** [comment]
> > [Qv2ray](https://github.com/Qv2ray/Qv2ray) 已经停更，建议更换其他工具如 [v2rayA](https://github.com/v2rayA/v2rayA)。
> 
> 提 issue/comment 前请先认真阅读[文档](https://archlinuxstudio.github.io/ArchLinuxTutorial/#/rookie/fxckGFW?id=%e6%9c%89%e5%85%b3-qv2ray-%e7%9a%84%e6%9b%bf%e4%bb%a3)

和文档写的意思还是有点不一样把，现在是前几天2021-8-17，作者正式宣布不搞了.文档只是提到4月份撕逼的事情。

**Comment by TakoTakoo** [comment]
This is a known issue, thanks for the reply
