### ISSUE TITLE
只推荐 pacman 安装还是同时提供 pacman 和 AUR 安装方式？

### ISSUE THREAD

**Issue by CyrusYip** [ArchLinuxStudio/ArchLinuxTutorial#63]
以[办公日常](https://archlinuxstudio.github.io/ArchLinuxTutorial/#/play&office/office)为例，这里有不少 AUR 软件 archlinuxcn 仓库或官方仓库都有，比如：

- weechat
- slack-desktop
- onlyoffice-bin
- joplin
- joplin-desktop
- zotero
- megasync

教程只写了 yay 安装方式或链接。对于同时存在于 AUR 和软件仓库的软件包，本教程应该推荐什么安装方式呢？这里有三种可能：

- 只推荐 yay
- 只推荐 pacman
- 两者都推荐

我个人倾向「只推荐 pacman」，「两者都推荐」也行。理由是「用 pacman 安装二进制包更快，还不需要安装打包软件需要的依赖」。

**Comment by TakoTakoo** [comment]
I am not very clear what you want to express.

**Comment by CyrusYip** [comment]
如果一个软件在仓库里，就把 yay 安装改为 pacman 安装。例如把`yay -S onlyoffice-bin` 替换为 `sudo pacman -S onlyoffice-bin`。

**Comment by crafter695565** [comment]
> 如果一个软件在仓库里，就把 yay 安装改为 pacman 安装。例如把`yay -S onlyoffice-bin` 替换为 `sudo pacman -S onlyoffice-bin`。

这issue可以关了，请你先了解一下，yay会优先使用pacman搜索和安装软件包，pacman找不到才会去aur找，如果一个包同时存在于pacman和aur，用yay和用pacman的效果是一模一样的，不存在你说的情况

**Comment by CyrusYip** [comment]
@teaper @crafter695565 谢谢两位指正，我之前以为 yay 只安装 AUR 的包，原来 yay 默认优先安装仓库的包，学习了。我刚刚查了下 yay 的帮助界面，原来可以指定软件源为仓库或 AUR。

总结一下 yay 安装软件的方式：

```bash
yay -S onlyoffice-bin              # 如果仓库有就安装，没有才从 AUR 安装
yay -S onlyoffice-bin --repo  # 只从仓库安装
yay -S onlyoffice-bin --aur    # 只从 AUR 安装，--aur 可简写为 -a
```
