### ISSUE TITLE
捉虫：办公日常

### ISSUE THREAD

**Issue by ImBearChild** [ArchLinuxStudio/ArchLinuxTutorial#83]
[办公日常](https://archlinuxstudio.github.io/ArchLinuxTutorial/#/play&office/office)提到 Zotero 是 Electron 应用的说法是错误的，Zotero 使用的是老版 Firefox 的那一套。

**Comment by ryosukeeeeee** [comment]
@ImBearChild 感谢你的指出。我们会进行修改，并加强对文档的审核。

**Comment by ryosukeeeeee** [comment]
fix in 77c9de3077e699e5946528e9686e1cc0c62af2cc

**Comment by ImBearChild** [comment]
没有想到会如此神速的解决，失敬失敬。
