### ISSUE TITLE
建议默认去掉基础安装第16步grub-install命令的--removable选项

### ISSUE THREAD

**Issue by ibb233** [ArchLinuxStudio/ArchLinuxTutorial#85]
grub-install加了--removable选项后系统无法在旧电脑（主板支持efi）上efi方式引导，BIOS里没有启动条目。去掉这个选项就可以了，BIOS是2012年的。

**Comment by ryosukeeeeee** [comment]
@ibb233 I think this is unlikely to happen. If you use the option --removable then GRUB will be installed to esp/EFI/BOOT/BOOTX64.EFI (or esp/EFI/BOOT/BOOTIA32.EFI for the i386-efi target), they are the fallback path, with the best compatibility. Are you using Windows on your computer at the same time?

**Comment by ibb233** [comment]
> @ibb233 I think this is unlikely to happen. If you use the option --removable then GRUB will be installed to esp/EFI/BOOT/BOOTX64.EFI (or esp/EFI/BOOT/BOOTIA32.EFI for the i386-efi target), they are the fallback path, with the best compatibility. Are you using Windows on your computer at the s

**Comment by ibb233** [comment]
> @ibb233 I think this is unlikely to happen. If you use the option --removable then GRUB will be installed to esp/EFI/BOOT/BOOTX64.EFI (or esp/EFI/BOOT/BOOTIA32.EFI for the i386-efi target), they are the fallback path, with the best compatibility. Are you using Windows on your computer at the same time?

我没在用Windows。一开始按照教程安装完Arch后BIOS里没有启动条目并且不能启动，grub-install去掉--removable参数以后启动条目就出现了。电脑是2013年上市的打人硕的x450vc，如果您也有可以测试一下。

**Comment by ryosukeeeeee** [comment]
@ibb233 If you remove the --removable parameter and restart, in fact nothing will change. Thanks for the report, I'll keep an eye out for if anyone else experiencing this.

**Comment by ryosukeeeeee** [comment]
@ibb233  Thanks for the report, I'll keep an eye out for if anyone else experiencing this.

**Comment by ryosukeeeeee** [comment]
https://wiki.archlinux.org/title/GRUB#Default/fallback_boot_path

**Comment by ibb233** [comment]
> https://wiki.archlinux.org/title/GRUB#Default/fallback_boot_path

我执行“grub-install --target=x86_64-efi --efi-directory=esp --removable”这条命令后efi分区里EFI文件夹里只有BOOT文件夹，在新电脑上可以启动，旧电脑不行。去掉“--removable"后重新执行，EFI文件夹里多了个GRUB文件夹，并且在旧电脑上可以启动了。与此处的archwiki情况不一样

/efi
└── EFI
    ├── BOOT
    │   └── BOOTX64.EFI
    └── GRUB
        └── grubx64.efi

grub手册里对”--removable"只提到了“For removable installs you have to use ‘--removable’ and specify both
‘--boot-directory’ and ‘--efi-directory”，并没有提到这个选项对兼容性的影响，一般安装arch也没有“removable"的需求，所以建议删除这个选项。

**Comment by ryosukeeeeee** [comment]
@ibb233  You can peruse the link I sent above. Below is the screenshot:

![image](https://user-images.githubusercontent.com/94822169/152494445-815a4a06-d8e7-42bc-90fa-a16f17cc774b.png)

--removable, this parameter can improve compatibility, it is a FACT and has been verified by many people. As for the situation you mentioned, I have not encountered it, nor have I seen reports from others. I'll be watching to see if something like this happens again.

**Comment by ibb233** [comment]
Arch wiki和grub2 manual都没提到“--removable"可以提高兼容性，它只是解决了特定的问题，并不普遍适用所有情况。也许其他和我遇到同样问题的人用别的方法解决了，或者他们放弃了。

**Comment by ryosukeeeeee** [comment]
@ibb233 我从更多的人处收到了此问题的报告, 你是对的, 我将对此问题进行修改.

**Comment by ibb233** [comment]
> @ibb233 我从更多的人处收到了此问题的报告, 你是对的, 我将对此问题进行修改.

上次忘说了，我的笔记本是uefi with csm，不是纯uefi。

**Comment by yibochen38** [comment]
-removable  parameter is a must for people who want to carry their system around on a removable hard disk. After my testing, it is possible to make the system plug-and-play with a removable hard disk in this way. The effect is that the system on your removable hard disk can also appear when you plug in the hard disk when selecting the startup items. Without this parameter, after a single unplug and plug, the system will no longer be present in the startup items

https://github.com/user-attachments/assets/9095676f-c020-4b62-bce3-345f4b491393
