### ISSUE TITLE
I apologize for the infringement of your article.

### ISSUE THREAD

**Issue by meng-luo** [ArchLinuxStudio/ArchLinuxTutorial#88]
In the Chinese community, disrespect for the CC license often occurs, and this is already the norm. There is nothing we can do, except to post these websites URL that does not respect the CC license here.

* https://www.ysbrid.top/post/arch-1/

I am the founder of this website. Because I changed to a new website, the website has not been maintained for a long time. I abandoned it long ago, and the content of the article has expired. Until today, I received a private letter, and I didn't notice that I used to reprint your website on the website without indicating the source, which infringed your copyright. I have deleted the content involved in the website change, and I am also very disgusted with unauthorized modification, transportation and copyright infringement. If I hadn't been reminded by others this time. What I have done has caused you discomfort or even disgust. I am very sorry for this. If you need compensation or other requirements, please feel free to contact me. I am extremely sorry.

_Originally posted by @ghost in https://github.com/ArchLinuxStudio/ArchLinuxTutorial/issues/68#issuecomment-966805272_

**Comment by ryosukeeeeee** [comment]
@meng-luo 

This project use the CC BY NC ND license, that means you when you reproduce these articles, you can not modify, can not for commercial use, and should indicate the source.

I accept your apology, it's very good that you were finally able to show respect for the license. Besides you, there are plenty of people who are violating this project's license and thinks it's not a big deal.

As for the reply from the ghost(former man in charge) of mentioning your website in that issue, I don't have permission to edit.
