### ISSUE TITLE
触摸板的部分功能失灵（单指触击、双指触击、....）

### ISSUE THREAD

**Issue by Brannua** [ArchLinuxStudio/ArchLinuxTutorial#90]
大佬您好，

新安装的系统，触摸板单指和双指相关的功能失灵了，求助

OS: Arch Linux x86_64
Host: Swift SF314-511 v1.10
Kernel: 5.16.10-arch1-1
DE: Plasma 5.24.1
CPU: 11th Gen Intel i5-1135G7

**Comment by ryosukeeeeee** [comment]
@Brannua Try to install package xf86-input-synaptics .

https://wiki.archlinux.org/title/Laptop/Acer#Swift

**Comment by Brannua** [comment]
> @Brannua Try to install package xf86-input-synaptics .
> 
> https://wiki.archlinux.org/title/Laptop/Acer#Swift

谢谢大佬，由于时间紧急没有测试您提供的方案，我暂时使用了 manjaro，一切正常了，谢谢大佬
