### ISSUE TITLE
Feature:希望添加分區加密教程

### ISSUE THREAD

**Issue by Ra2-IFV** [ArchLinuxStudio/ArchLinuxTutorial#94]
對於在牆國內的用戶來說，很可能隨時會被警察抄家，需要加密來作爲防護。
Ubuntu在安裝時就自帶了加密的選項，希望能添加個安裝時加密分區的教程～

**Comment by ryosukeeeeee** [comment]
@Ra2-IFV 感谢你的建议 我们会持续增加和更新隐私保护方面的内容。  实际上 更多关于此方面的技术 可以参考

https://github.com/ArchLinuxStudio/ModernSecurityProtectionGuide

**Comment by LuoQinXuan** [comment]
个人看法:Ubuntu这个系统有颇多争议：其中之一在于：Ubuntu中可能夹带一些一些spyware(间谍软件)。毕竟是公司的产物。有可能Ubuntu会手机用户所作所为生成日志，比方说：每一次安装好桌面版Ubuntu之后都会有一个弹窗告诉你：发送信息给Canonical。一般情况下我都会选择否。只是个人觉得：真正社区的发行版应该不会出现这种消息。但是学校一直教学使用的是Ubuntu没办法。现在已经切换到了Debian stable下。但是这也并不意味着Debian真的没有问题。只是是否在用户接受的范围之内了
