### ISSUE TITLE
Problem: Can not load pages in the mainland with default cdn

### ISSUE THREAD

**Issue by bLueriVerLHR** [ArchLinuxStudio/ArchLinuxTutorial#99]
### Brief description of problem

Fail to load docsify while using mainland network.

Fail to load pages with an error "Docsify is not defined at sitetime".

#### Environment
- [x] chrome
- [x] firefox
- [x] edge

XD

#### Probable Cause

The default cdn link jsdelivr may be blocked.

#### Description

I first met this problem on my own website when I try to visit it from school network. And I try to change the cdn from jsdelivr to bootcdn to handle this problem. Docsify can be loaded but it seems that the other plugins' cdn are still blocked. (It doesn't matter thought, since I can continue to find and change the cdn.)

But now when I try to read articles on ALT(ArchLinuxTutorial) using mainland network, I just saw an error "Docsify is not defined at sitetime" in console continuous appearing and fail to load the page as a result. I read the page's code and found that the cdn is also the default one. Although I can try to visit using other methods, I wish to read it without any restriction.

By the way, when I tried to visit docsify's official website, I also met this problem.

**Comment by ryosukeeeeee** [comment]
@bLueriVerLHR Thank you for the report. But we will not compromise the network blockade of the Chinese mainland government, so as to use a cdn service controlled by a mainland Chinese enterprise. We have added a reminder about network blocking to this commit, hoping it will make more people aware of the evil deeds of a dictatorship.  
https://github.com/ArchLinuxStudio/ArchLinuxTutorial/commit/7a43619fd5b766cb41cfeba44ba5c0062f6a6b8d

**Comment by ryosukeeeeee** [comment]
@bLueriVerLHR  We do a trade off in https://github.com/ArchLinuxStudio/ArchLinuxTutorial/commit/478494305015e456c35a787297c47812cb635e2c, please check again.

**Comment by bLueriVerLHR** [comment]
Its a good idea, and jsdelivr also returns to normal. Appreciate your persistence. 👍
